### ISSUE TITLE
insert e2e testing to productService

### ISSUE THREAD

**Issue by caglarcercinli** [takimbirprojeler/eticaret.backend.node#65]

**Comment by KerimCETINBAS** [comment]
we should mock couchbase service at product.controller.spec.ts

**Comment by caglarcercinli** [comment]
> 
well we should make a decision about it. we ll have 3 types of tests: unit,e2e and integration. which file for which testing?

**Comment by KerimCETINBAS** [comment]
it depends on file name,`` service.spec.ts `` for unit testing
``service.e2e-spec.ts // e2e testing``

i think we should do our integrating test outside of codebase
